#apiVersion: v1
#kind: Namespace
#metadata:
#  name: devops-ramp-up-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-frontend
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend #backend connection
    spec:
      containers:
      - image: davidsanchez21/endabank-frontend:latest
        name: frontend
        ports:
        - containerPort: 3000
        env:
        - name: BASE_URL
          value: "10.107.11.21:3000" #cluster-ip (backend-service:3000)

  replicas: 2