apiVersion: v1
kind: Service
metadata:  
  name: node-port-frontend-ramp-up
spec:
  type: NodePort
  selector:    
    app: frontend-ramp-up
  ports:  
    - port: 3030
      targetPort: 3030
      nodePort: 30021
      protocol: TCP